server:
  port: 1100
spring:
  application:
    name: service-session-zuul
zuul:
  ignoredServices: '*' #\u5FFD\u7565\u6240\u6709\u672A\u914D\u7F6E\u7684service
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    redis-session-service:
      path: /user-session/**
      serviceId: service-session-redis
      sensitiveHeaders: "*"
ribbon: #ribbon\u8D1F\u8F7D\u5747\u8861\u53C2\u6570\u914D\u7F6E
  ReadTimeout: 5000
  ConnectTimeout: 5000
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/